# Generated by Django 2.1 on 2018-10-08 12:51

from django.db import migrations, models
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('tagify', '0002_auto_20181008_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='image',
            field=models.ImageField(upload_to=tagify.models.path_and_rename),
        ),
    ]
