# Generated by Django 2.1 on 2018-10-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagify', '0003_auto_20181008_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
