# Generated by Django 2.1 on 2018-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagify', '0004_auto_20181008_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='image',
            field=models.ImageField(upload_to='varun'),
        ),
    ]
