# Generated by Django 2.1 on 2018-11-02 14:04

from django.db import migrations, models
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('tagify', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='image',
            field=models.ImageField(upload_to=tagify.models.path_and_rename),
        ),
    ]
